/**
 * Push the Prisma schema to Turso via the libSQL HTTP client.
 * (The standard `prisma db push` doesn't support libsql:// URLs in the CLI.)
 *
 * Reads the SQL from /tmp/schema.sql (generated by `prisma migrate diff`)
 * and executes each statement via @libsql/client.
 */
import { createClient } from '@libsql/client';
import { readFileSync } from 'fs';

const url = process.env.DATABASE_URL!;
const authToken = process.env.TURSO_AUTH_TOKEN;

if (!url) {
  console.error('DATABASE_URL is required');
  process.exit(1);
}

if (!url.startsWith('libsql://') && !url.startsWith('https://')) {
  console.error(`Unexpected URL scheme: ${url}`);
  process.exit(1);
}

const client = createClient({ url, authToken });

async function main() {
  const sql = readFileSync('/tmp/schema.sql', 'utf8');
  // Prisma emits statements separated by ");\n\n-- Comment". Split on
  // ");\n" and re-append ");" to each statement. Filter to only CREATE statements
  // (skip pure comment-only chunks).
  const rawStatements = sql.split(');\n');
  const statements = rawStatements
    .map((s) => s.trim())
    .filter((s) => s.length > 0 && /CREATE\s+(TABLE|INDEX|UNIQUE)/i.test(s))
    .map((s) => s.endsWith(');') ? s : s + ');');

  console.log(`Executing ${statements.length} SQL statements against Turso...`);

  for (let i = 0; i < statements.length; i++) {
    const stmt = statements[i];
    try {
      await client.execute(stmt + ';');
      console.log(`  ✓ ${stmt.slice(0, 60).replace(/\n/g, ' ')}...`);
    } catch (e: any) {
      // SQLite: "table already exists" is fine — we're re-pushing
      if (e.message?.includes('already exists')) {
        console.log(`  ⊙ already exists: ${stmt.slice(0, 60).replace(/\n/g, ' ')}...`);
      } else {
        console.error(`  ✗ Failed: ${stmt.slice(0, 80).replace(/\n/g, ' ')}...`);
        console.error(`    Error: ${e.message}`);
      }
    }
  }

  // Verify tables exist
  const tables = await client.execute(
    "SELECT name FROM sqlite_master WHERE type='table' ORDER BY name"
  );
  console.log(`\n✅ Tables in Turso database:`);
  for (const row of tables.rows) {
    console.log(`  - ${(row as any).name}`);
  }
}

main().catch((e) => {
  console.error('Failed:', e);
  process.exit(1);
});
